"""remove many to mant table, add book_id in ChunkORM

Revision ID: cbc17b18a9e8
Revises: 5818d29049ff
Create Date: 2026-09-29 15:50:24.591616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc17b18a9e8'
down_revision: Union[str, Sequence[str], None] = '5818d29049ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks_to_books')
    op.add_column('chunks', sa.Column('book_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chunks', 'books', ['book_id'], ['book_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'book_id')
    op.create_table('chunks_to_books',
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name=op.f('chunks_to_books_book_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('chunks_to_books_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', name=op.f('chunks_to_books_pkey')),
    sa.UniqueConstraint('chunk_id', 'book_id', name=op.f('unique_chunk_to_book'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
