"""add model embedding vector in ChunkORM

Revision ID: 2cdcb6ea7312
Revises: 330a3a943e09
Create Date: 2026-10-08 10:42:08.658247

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdcb6ea7312'
down_revision: Union[str, Sequence[str], None] = '330a3a943e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
