"""add HistoryORM model

Revision ID: 34ec2aecf8b5
Revises: cbc17b18a9e8
Create Date: 2026-09-30 23:33:16.362676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ec2aecf8b5'
down_revision: Union[str, Sequence[str], None] = 'cbc17b18a9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('llm_response', sa.Text(), nullable=False),
    sa.Column('dialog_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('ix_histories_user_id_dialog_time', 'histories', ['user_id', 'dialog_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_histories_user_id_dialog_time', table_name='histories')
    op.drop_table('histories')
    # ### end Alembic commands ###
