"""add user_role field into UserORM

Revision ID: 6671ab0c9fa2
Revises: a8e6156f2a72
Create Date: 2026-09-09 12:36:58.942145

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6671ab0c9fa2'
down_revision: Union[str, Sequence[str], None] = 'a8e6156f2a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = ENUM('ADMIN', 'USER', name='UserRoles', create_type=True)
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('user_role', sa.Enum('ADMIN', 'USER', name='UserRoles'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    ENUM(name='UserRoles').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
