"""add model name in history

Revision ID: 330a3a943e09
Revises: 34ec2aecf8b5
Create Date: 2026-10-01 23:45:47.908990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330a3a943e09'
down_revision: Union[str, Sequence[str], None] = '34ec2aecf8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('llm_model', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories', 'llm_model')
    # ### end Alembic commands ###
